### ISSUE TITLE
Duplicate puzzles

### ISSUE THREAD

**Issue by Radcliffe** [dachev/sudoku#10]
I am trying to use this software to produce a database of Sudoku puzzles and solutions, but I am getting a large number of duplicates. Of course there are only a finite number of possible puzzles, but if I generate a million puzzles then I would expect very few or no duplicates. Is there something that I can do to avoid duplicates, or can the code be modified to allow for generating a larger number of unique puzzles?

**Comment by dachev** [comment]
PR merged
