### ISSUE TITLE
How to set difficulty for Sudoku 

### ISSUE THREAD

**Issue by Melvynx** [dachev/sudoku#6]
Hi !

I need make a Sudoku generator.

I actually use you're framework for generate this, but I can't set a difficulty to them.
I would like to make them easier.

Can we do this, and how ?

Thanks to you're Job 😁

**Comment by dachev** [comment]
Hi @MelvynX. Currently, there is no way to specify the desired difficulty level when generating a new Sudoku board. However, you can call the generate function multiple times until you get the result you need. Depending on your app context, you might be even able to do this work on the background and feed the results to a queue of pre-generated boards for each difficulty level. Then, you can draw from it when you need.
